# Generated by Django 5.2.5 on 2025-08-11 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('description', models.CharField(max_length=255, verbose_name='توضیحات')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category_icons/', verbose_name='آیکن')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('description', models.CharField(max_length=255, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='تصویر')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='menu.category', verbose_name='محصول')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='menu.product', verbose_name='محصول')),
            ],
        ),
    ]
