# Generated by Django 5.2.5 on 2025-08-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='نام'),
        ),
    ]
