# Generated by Django 5.2.5 on 2025-08-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_category_description_alter_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات'),
        ),
    ]
